services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: src/api
      FLASK_ENV: development
