services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'

  flask:
    env_file: .env
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
