version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis-data:/data
    container_name: redis
    command: redis-server --port 6379 --appendonly yes  --protected-mode no  --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
    platform: linux/amd64

  web:
    container_name: viberary
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    ports:
      - '5001:5000'
    volumes:
      - ./:/viberary
      - ./viberary/src/training_data:/training_data
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    platform: linux/amd64
    command: gunicorn --bind 0.0.0.0:5000 src.api.wsgi:app


volumes:
  redis-data:


