version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis-data:/data
    container_name: redis
    command: redis-server --port 6379 --appendonly yes  --protected-mode no  --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so

  web:
    container_name: viberary
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - '80:8000'
    volumes:
      - ./:/viberary
      - ./viberary/src/training_data:/training_data
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis


volumes:
  redis-data:


