services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'

  web:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
